apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
      - name: backend-springboot
        image: ghcr.io/shclub/edu12-backend 
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        - name: SPRING_DATASOURCE_USERNAME
          value: "edu"
        - name: SPRING_DATASOURCE_PASSWORD
          #value: "caravan"
          value: "edu1234"
        - name: SPRING_DATASOURCE_URL
          #value: "jdbc:mariadb://helm-db-mariadb.edu31.svc.cluster.local:3306/edu"
          value: "jdbc:mariadb://my-release-mariadb:3306/edu"
          #value: "jdbc:mariadb://211.34.231.84:32065/edu"
        ports:
        - containerPort: 8080
