apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
      - name: backend-springboot
        image: ghcr.io/shclub/edu12-4 
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:elastic-apm-agent-1.43.0.jar -Delastic.apm,server_url=apm-server.elastic:8200 -Delastic.apm.environment=dev -Dservice_name=backend-springboot -Delastic.apm.secret_token="    ## secret_token 값은 비워둠
          #value: "-javaagent:/app/libs/elastic-apm-agent-1.43.0.jar  -Delastic.apm.service_name=icis-apigw-$(ZONE)  -Delastic.apm.server_urls=http://apm-server-route-sa-dedi.  
        #- name: SPRING_DATASOURCE_USERNAME
        #  value: "edu"
        #- name: SPRING_DATASOURCE_PASSWORD
          #value: "caravan"
        #  value: "edu1234"
        #- name: SPRING_DATASOURCE_URL
          #value: "jdbc:mariadb://helm-db-mariadb.edu31.svc.cluster.local:3306/edu"
          #value: "jdbc:mariadb://my-release-mariadb:3306/edu"
          #value: "jdbc:mariadb://211.34.231.84:32065/edu"
        ports:
        - containerPort: 8080
