apiVersion: v1	
kind: Service	
metadata:	
  name: backend-springboot
  labels: # service monitor 의 selector 를 위하여 생성
    app: backend-springboot
spec:	
  ports:	
  - port: 80	
    targetPort: 8080
    name: http
  selector:	
    app: backend-springboot
  type: ClusterIP
